---
- name: 3.4.1.1 Ensure a Firewall package is installed (Scored)
  package:
    name: "{{ cis_firewall_package }}"
    state: present
  when:
    - cis_firewall_package_installed | bool

- name: 3.4.2.1 Ensure firewalld service is enabled and running (Scored)
  service:
    name: firewalld
    state: started
    enabled: yes
  when:
    - cis_firewalld_enabled_and_running | bool

- name: 3.4.2.2 Ensure nftables is not enabled (Scored)
  service:
    name: nftables
    state: stopped
    enabled: false
    masked: yes
  when:
    - cis_nftables_not_enabled | bool
