---
- name: 3.1.1 Ensure IP forwarding is disabled (Scored)
  sysctl:
    name: net.ipv4.ip_forward
    value: "0"
    state: present
    reload: yes
  when: cis_ip_forwarding_disabled | bool

- name: 3.1.1 Ensure IP forwarding is disabled (Scored)
  sysctl:
    name: net.ipv6.ip_forward
    value: "0"
    state: present
    reload: yes
  when: cis_ip_forwarding_disabled | bool
