---
- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: "0"
    state: present
  notity:
    - net.ipv4.route.flush
  when:
   - cis_source_routed_packets_not_accepted | bool

- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: "0"
    state: present
  notity:
    - net.ipv4.route.flush
  when:
   - cis_source_routed_packets_not_accepted | bool

- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.all.accept_source_route
    value: "0"
    state: present
  notity:
    - net.ipv6.route.flush
  when:
   - cis_source_routed_packets_not_accepted | bool

- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.default.accept_source_route
    value: "0"
    state: present
  notity:
    - net.ipv6.route.flush
  when:
   - cis_source_routed_packets_not_accepted | bool

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: "0"
    state: present
  notity:
    - net.ipv4.route.flush
  when:
    - cis_icmp_redirects_not_accepted | bool

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: "0"
    state: present
  notity:
    - net.ipv4.route.flush
  when:
    - cis_icmp_redirects_not_accepted | bool

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: "0"
    state: present
  notity:
    - net.ipv6.route.flush
  when:
    - cis_icmp_redirects_not_accepted | bool

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: "0"
    state: present
  notity:
    - net.ipv6.route.flush
  when:
    - cis_icmp_redirects_not_accepted | bool
