---
- name: 3.3.1 Ensure DCCP is disabled (Scored)
  copy:
    content: "install dccp /bin/true"
    dest: /etc/modprobe.d/dccp.conf
    mode: "0644"
  when:
    - cis_dccp_disabled | bool

- name: 3.3.1 Ensure DCCP is disabled (Scored)
  modprobe:
    name: dccp
    state: absent
  when:
    - cis_dccp_disabled | bool
