---
- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: "0"
    state: present
  check_mode: yes
  register: cis_source_routed_packets_not_accepted_test_one
  failed_when:
    - cis_source_routed_packets_not_accepted_test_one is changed
  when:
   - cis_source_routed_packets_not_accepted | bool

- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: "0"
    state: present
  check_mode: yes
  register: cis_source_routed_packets_not_accepted_test_two
  failed_when:
    - cis_source_routed_packets_not_accepted_test_two is changed
  when:
   - cis_source_routed_packets_not_accepted | bool

- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.all.accept_source_route
    value: "0"
    state: present
  check_mode: yes
  register: cis_source_routed_packets_not_accepted_test_three
  failed_when:
    - cis_source_routed_packets_not_accepted_test_three is changed
  when:
   - cis_source_routed_packets_not_accepted | bool


- name: 3.2.1 Ensure source routed packets are not accepted (Scored)
  sysctl:
    name: net.ipv6.conf.default.accept_source_route
    value: "0"
    state: present
  check_mode: yes
  register: cis_source_routed_packets_not_accepted_test_four
  failed_when:
    - cis_source_routed_packets_not_accepted_test_four is changed
  when:
   - cis_source_routed_packets_not_accepted | bool
