---
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

# For now, only collect service_facts on non-Ubuntu due to:
# https://github.com/ansible/ansible/issues/71140
# - name: populate service facts
#   service_facts:

- name: gather the rpm package facts
  package_facts:

- name: include distribution specific version
  include: "{{ ansible_distribution ~ '-' ~ ansible_distribution_major_version }}/main.yml"
