---
- name: include assert.yml
  include_tasks: assert.yml

- name: populate service facts
  service_facts:

- name: include distribution specific version
  include: "{{ ansible_distribution ~ '-' ~ ansible_distribution_major_version }}/main.yml"
