---
- name: 1.3.1 Ensure sudo is installed (Scored)
  command: rpm -q sudo
  when:
    - cis_sudo_installed | bool

- name: 1.3.2 Ensure sudo commands use pty (Scored)
  command: "grep -Ei '^\\s*Defaults\\s+(\\[^#]+,\\s*)?use_pty' /etc/sudoers"
  failed_when: no
  register: cis_sudo_use_pty_test_one
  when:
    - cis_sudo_use_pty | bool

- name: 1.3.2 Ensure sudo commands use pty (Scored)
  command: "grep -Ei '^\\s*Defaults\\s+(\\[^#]+,\\s*)?use_pty' /etc/sudoers.d/*"
  failed_when: no
  register: cis_sudo_use_pty_test_two
  when:
    - cis_sudo_use_pty | bool

- name: 1.3.2 Ensure sudo commands use pty (Scored)
  assert:
    that:
      - cis_sudo_use_pty_test_one.stdout == "Defaults use_pty" or
        cis_sudo_use_pty_test_two.stdout == "Defaults use_pty"
  when:
    - cis_sudo_use_pty | bool

- name: 1.3.3 Ensure sudo log file exists (Scored)
  command: "grep -Ei '^\\s*Defaults\\s+([^#]+,\\s*)?logfile=' /etc/sudoers /etc/sudoers.d/*"
  register: cis_sudo_logfile_test
  when:
    - cis_sudo_logfile | bool

- name: 1.3.3 Ensure sudo log file exists (Scored)
  assert:
    that:
      - cis_sudo_logfile.stdout == 'Defaults logfile="/var/log/sudo.log"'
  when:
    - cis_sudo_logfile | bool
