---
- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  command: modprobe -n -v cramfs
  register: output
  when:
    - cis_cramfs_disabled | bool
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  command: lsmod | grep cramfs
  register: output
  when:
    - cis_cramfs_disabled | bool
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is disabled (Not Scored)
  command: modprobe -n -v vfat
  register: output
  when:
    - cis_vfat_disabled | bool
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is disabled (Not Scored)
  command: lsmod | grep vfat
  register: output
  when:
    - cis_vfat_disabled | bool
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  command: modprobe -n -v squashfs
  register: output
  when:
    - cis_squashfs_disabled | bool
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  command: lsmod | grep squashfs
  register: output
  when:
    - cis_squashfs_disabled | bool
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.3 Ensure mounting of udf filesystems is disabled (Scored)
  command: modprobe -n -v udf
  register: output
  when:
    - cis_udf_disabled | bool
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.3 Ensure mounting of udf filesystems is disabled (Scored)
  command: lsmod | grep udf
  register: output
  when:
    - cis_udf_disabled | bool
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.2 Ensure /tmp is configured (Scored)
  shell: mount | grep -E '\s/tmp\s'
  register: output
  when:
    - cis_tmp_configured | bool
  failed_when:
    - output.stdout_lines | length < 1

- name: 1.1.2 Ensure /tmp is configured (Scored)
  stat:
    path: /etc/fstab
  register: fstab
  when:
    - cis_tmp_configured | bool

- name: 1.1.2 Ensure /tmp is configured (Scored)
  shell: grep -E '\s/tmp\s' /etc/fstab | grep -E -v '^\s*#'
  register: output_fstab
  when:
    - cis_tmp_configured | bool
    - fstab.stat.exists | bool

- name: 1.1.2 Ensure /tmp is configured (Scored)
  command: systemctl is-enabled tmp.mount
  register: output_systemctl
  when:
    - cis_tmp_configured | bool

- name: 1.1.2 Ensure /tmp is configured (Scored)
  assert:
    that:
      - output_fstab.stdout_lines | length > 0 or
        output_systemctl.stdout in ["static", "enabled"]
  when:
    - cis_tmp_configured | bool
    - output_fstab.stdout_lines is defined

- name: 1.1.3 Ensure nodev option set on /tmp partition (Scored)
  shell: mount | grep -E '\s/tmp\s' | grep -v nodev
  register: output
  when:
    - cis_tmp_nodev | bool
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
  shell: mount | grep -E '\s/tmp\s' | grep -v nosuid
  register: output
  when:
    - cis_tmp_nosuid | bool
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.5 Ensure noexec option set on /tmp partition (Scored)
  shell: mount | grep -E '\s/tmp\s' | grep -v noexec
  register: output
  when:
    - cis_tmp_noexec | bool
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.6 Ensure separate partition exists for /var (Scored)
