---
- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  command: modprobe -n -v cramfs
  register: output
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  command: lsmod | grep cramfs
  register: output
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is disabled (Not Scored)
  command: modprobe -n -v vfat
  register: output
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is disabled (Not Scored)
  command: lsmod | grep vfat
  register: output
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  command: modprobe -n -v squashfs
  register: output
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  command: lsmod | grep squashfs
  register: output
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.3 Ensure mounting of udf filesystems is disabled (Scored)
  command: modprobe -n -v udf
  register: output
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.3 Ensure mounting of udf filesystems is disabled (Scored)
  command: lsmod | grep udf
  register: output
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.2 Ensure /tmp is configured (Scored)
  shell: mount | grep -E '\s/tmp\s'
  register: output
  failed_when:
    - output.stdout_lines | length < 1

- name: 1.1.2 Ensure /tmp is configured (Scored)
  shell: grep -E '\s/tmp\s' /etc/fstab | grep -E -v '^\s*#'
  register: output_fstab

- name: 1.1.2 Ensure /tmp is configured (Scored)
  command: systemctl is-enabled tmp.mount
  register: output_systemctl

- name: 1.1.2 Ensure /tmp is configured (Scored)
  assert:
    that:
      - output_fstab.stdout_lines | length > 0 or
        output_systemctl.stdout in ["static", "enabled"]

- name: 1.1.3 Ensure nodev option set on /tmp partition (Scored)
  shell: mount | grep -E '\s/tmp\s' | grep -v nodev
  register: output
  failed_when:
    - output.stdout_lines | lenghth > 0

- name: 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
  shell: mount | grep -E '\s/tmp\s' | grep -v nosuid
  register: output
  failed_when:
    - output.stdout_lines | lenghth > 0

- name: 1.1.5 Ensure noexec option set on /tmp partition (Scored)
  shell: mount | grep -E '\s/tmp\s' | grep -v noexec
  register: output
  failed_when:
    - output.stdout_lines | lenghth > 0
