---
- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  command: modprobe -n -v cramfs
  register: output
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  command: lsmod | grep cramfs
  register: output
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is disabled (Not Scored)
  command: modprobe -n -v vfat
  register: output
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is disabled (Not Scored)
  command: lsmod | grep vfat
  register: output
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  command: modprobe -n -v squashfs
  register: output
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  command: lsmod | grep squashfs
  register: output
  failed_when:
    - output.stdout_lines | length > 0

- name: 1.1.1.3 Ensure mounting of udf filesystems is disabled (Scored)
  command: modprobe -n -v udf
  register: output
  failed_when:
    - '"install /bin/true" not in output.stdout'

- name: 1.1.1.3 Ensure mounting of udf filesystems is disabled (Scored)
  command: lsmod | grep udf
  register: output
  failed_when:
    - output.stdout_lines | length > 0
