---
- name: 1.7.1.1 Ensure SELinux is installed (Scored)
  package:
    name: libselinux
    state: present
  register: cis_selinux_installed_test
  check_mode: yes
  when:
    - cis_selinux_installed

- name: 1.7.1.1 Ensure SELinux is installed (Scored)
  assert:
    that:
      - cis_selinux_installed_test is not changed
    quiet: yes
  when:
    - cis_selinux_installed

- name: 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration (Scored)
  command: grep -E 'kernelopts=(\S+\s+)*(selinux=0|enforcing=0)+\b' /boot/grub2/grubenv
  register: cis_selinux_not_disabled_test
  when:
    - cis_selinux_not_disabled

- name: 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration (Scored)
  assert:
    that:
      - cis_selinux_not_disabled_test.stdout | length == 0
    quiet: yes
  when:
    - cis_selinux_not_disabled

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  command: grep -E '^\s*SELINUXTYPE=(targeted|mls)\b' /etc/selinux/config
  register: cis_selinux_policy_configured_test_one
  when:
    - cis_selinux_policy_configured

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  assert:
    that:
      - cis_selinux_policy_configured_test_one.stdout in ["SELINUXTYPE=targeted", "SELINUXTYPE=mls"]
    quiet: yes
  when:
    - cis_selinux_policy_configured

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  shell: set -o pipefail && sestatus | grep Loaded
  register: cis_selinux_policy_configured_test_two
  when:
    - cis_selinux_policy_configured

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  assert:
    that:
      - cis_selinux_policy_configured_test_two.stdout in ["targeted", "mls"]
    quiet: yes
  when:
    - cis_selinux_policy_configured
