---
- name: 1.5.1 Ensure permissions on bootloader config are configured (Scored)
  stat:
    path: "{{ item }}"
  register: cis_permissions_bootloader_test
  loop:
    - /boot/grub2/grub.cfg
    - /boot/grub2/grubenv

- name: 1.5.1 Ensure permissions on bootloader config are configured (Scored)
  assert:
    that:
      - item.stat.uid == 0
      - item.stat.gid == 0
      - not item.stat.wgrp == no
      - not item.stat.rgrp == no
      - not item.stat.xgrp == no
      - not item.stat.woth == no
      - not item.stat.roth == no
      - not item.stat.xoth == no
  when:
    - item.stat.exists | bool
  loop: "{{ cis_permissions_bootloader_test.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: 1.5.2 Ensure bootloader password is set (Scored)
  stat:
    path: /boot/grub2/user.cfg
  register: cis_bootloader_password_test_one
  when:
    - cis_bootloader_password_set | bool

- name: 1.5.2 Ensure bootloader password is set (Scored)
  command: grep "^\\s*GRUB2_PASSWORD" /boot/grub2/user.cfg
  failed_when: no
  register: cis_bootloader_password_test_two
  when:
    - cis_bootloader_password_set | bool
    - cis_bootloader_password_test_one.stat.exists

- name: 1.5.2 Ensure bootloader password is set (Scored)
  assert:
    that:
      - cis_bootloader_password_test_one.stat.exists
      - '"GRUB2_PASSWORD=" in cis_bootloader_password_test_two.stdout'
  when:
    - cis_bootloader_password_set | bool
