---
- name: 1.10 Ensure system-wide crypto policy is not legacy (Scored)
  command: grep -E -i '^\s*LEGACY\s*(\s+#.*)?$' /etc/crypto-policies/config
  register: cis_crypto_policy_not_legacy_test
  failed_when:
    - cis_crypto_policy_not_legacy_test.stdout | length > 0
  when:
    - cis_crypto_policy_not_legacy | bool
