---
- name: include initial_setup.yml
  include: initial_setup.yml

- name: include configure_software_updates.yml
  include: configure_software_updates.yml

- name: include configure_sudo.yml
  include: configure_sudo.yml

- name: include filesystem_integrity_checking.yml
  include: filesystem_integrity_checking.yml
