---
- name: 1.8.1.1 Ensure message of the day is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/motd
  check_mode: yes
  register: cis_message_of_the_day_configured_test_one
  failed_when:
    - cis_message_of_the_day_configured_test_one is changed
  when:
    - cis_message_of_the_day_configured | bool

# - name: 1.8.1.1 Ensure message of the day is configured properly (Scored)
#   command: grep -E -i "(\\\v|\\\r|\\\m|\\\s|$(grep '^ID=' /etc/os-release | cut -d= -f2 | sed -e 's/"//g'))" /etc/motd
#   check_mode: yes
#   register: cis_message_of_the_day_configured_test_two
#   failed_when:
#     - cis_message_of_the_day_configured_test_two.stdout | length > 0
#   when:
#     - cis_message_of_the_day_configured | bool

- name: 1.8.1.2 Ensure local login warning banner is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/issue
  check_mode: yes
  register: cis_local_login_banner_configured_test_one
  failed_when:
    - cis_local_login_banner_configured_test_one is changed
  when:
    - cis_local_login_banner_configured | bool

# - name: 1.8.1.2 Ensure local login warning banner is configured properly (Scored)
#   command: grep -E -i "(\\\v|\\\r|\\\m|\\\s|$(grep '^ID=' /etc/os-release | cut -d= -f2 | sed -e 's/"//g'))" /etc/issue
#   check_mode: yes
#   register: cis_local_login_banner_configured_test_two
#   failed_when:
#     - cis_local_login_banner_configured_test_two.stdout | length > 0
#   when:
#     - cis_local_login_banner_configured | bool

- name: 1.8.1.3 Ensure remote login warning banner is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/issue.net
  check_mode: yes
  register: cis_remote_login_banner_configured_test_one
  failed_when:
    - cis_remote_login_banner_configured_test_one is changed
  when:
    - cis_remote_login_banner_configured | bool
