---
- name: 4.1.1.1 Ensure auditd is installed (Scored)
  package:
    name: audit
    state: present
  when:
    - cis_auditd_installed | bool

- name: 4.1.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    state: started
    enabled: yes
  when:
    - cis_auditd_service_enabled | bool

- name: 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((:?(?!audit=1).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 audit=1"'
    validate: /bin/sh %s
    mode: "0664"
  notify:
    - run grub2-mkconfig
  when:
    - cis_auditing_processes_prior_start | bool

- name: 4.1.1.4 Ensure audit_backlog_limit is sufficient (Scored)
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((:?(?!audit_backlog_limit=.*).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 audit_backlog_limit=8192"'
    validate: /bin/sh %s
    mode: "0664"
  notify:
    - run grub2-mkconfig
  when:
    - cis_audit_backlog_limit_sufficient | bool

- name: 4.1.2.1 Ensure audit log storage size is configured (Scored)
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^max_log_file = '
    line: "max_log_file = {{ cis_audit_log_storage_size }}"
  notify:
    - restart auditd
  when:
    - cis_audit_log_storage_size_configured | bool

- name: 4.1.2.2 Ensure audit logs are not automatically deleted (Scored)
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^max_log_file_action = '
    line: "max_log_file_action = keep_logs"
  notify:
    - restart auditd
  when:
    - cis_audit_logs_no_automatically_deleted | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^space_left_action = '
    line: "space_left_action = email"
  notify:
    - restart auditd
  when:
    - cis_system_disabled_audit_logs_full | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^action_mail_acct = '
    line: "action_mail_acct = root"
  notify:
    - restart auditd
  when:
    - cis_system_disabled_audit_logs_full | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^admin_space_left_action = '
    line: "admin_space_left_action = halt"
  notify:
    - restart auditd
  when:
    - cis_system_disabled_audit_logs_full | bool

- name: 4.1.3 Ensure changes to system administration scope (sudoers) is collected (Scored)
  lineinfile:
    path: /etc/audit/rules.d/scope.rules
    line: "{{ item }}"
  loop:
    - -w /etc/sudoers -p wa -k scope
    - -w /etc/sudoers.d/ -p wa -k scope
  notify:
    - reboot
  when:
    - cis_changed_to_system_administrator_scope_collected | bool

- name: 4.1.4 Ensure login and logout events are collected (Scored)
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    line: "{{ item }}"
  loop:
    - -w /var/log/faillog -p wa -k logins
    - -w /var/log/lastlog -p wa -k logins
  notify:
    - reboot
  when:
    - cis_login_and_login_events_collected | bool

- name: 4.1.5 Ensure session initiation information is collected (Scored)
  lineinfile:
    path: /etc/audit/rules.d/logins.rules
    line: "{{ item }}"
  failed_when:
    - -w /var/run/utmp -p wa -k session
    - -w /var/run/wtmp -p wa -k logins
    - -w /var/run/btmp -p wa -k logins
  notify:
    - reboot
  when:
    - cis_session_initiation_information_collected | bool

- name: 4.1.6 Ensure events that modify date and time information are collected (Scored)
  lineinfile:
    path: /etc/audit/rules.d/time-change.rules
    line: "{{ item }}"
  loop:
    - -a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change
    - -a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change
    - -a always,exit -F arch=b64 -S clock_settime -k time-change
    - -a always,exit -F arch=b32 -S clock_settime -k time-change
    - -w /etc/localtime -p wa -k time-change
  notify:
    - reboot
  when:
    - cis_events_modify_time_and_date_collected | bool

- name: 4.1.7 Ensure events that modify the system's Mandatory Access Controls are collected (Scored)
  lineinfile:
    path: /etc/audit/rules.d/MAC-policy.rules
    line: "{{ item }}"
  loop:
    - -w /etc/selinux/ -p wa -k MAC-policy
    - -w /usr/share/selinux/ -p wa -k MAC-policy
  notify:
    - reboot
  when:
    - cis_events_modifying_mac_collected | bool
