---
- name: 4.1.1.1 Ensure auditd is installed (Scored)
  package:
    name: audit
    state: present
  when:
   -  cis_auditd_installed | bool

- name: 4.1.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    state: started
    enabled: yes
  when:
    - cis_auditd_service_enabled | bool
