---
- name: 4.1.1.1 Ensure auditd is installed (Scored)
  package:
    name: audit
    state: present
  when:
    - cis_auditd_installed | bool

- name: 4.1.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    state: started
    enabled: yes
  when:
    - cis_auditd_service_enabled | bool

- name: 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((:?(?!audit=1).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 audit=1"'
    validate: /bin/sh %s
    mode: "0664"
  notify:
    - run grub2-mkconfig
  when:
    - cis_auditing_processes_prior_start | bool
