---
- name: 4.1.1.1 Ensure auditd is installed (Scored)
  package:
    name: audit
    state: present
  when:
    - cis_auditd_installed | bool

- name: 4.1.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    state: started
    enabled: yes
  when:
    - cis_auditd_service_enabled | bool

- name: 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((:?(?!audit=1).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 audit=1"'
    validate: /bin/sh %s
    mode: "0664"
  notify:
    - run grub2-mkconfig
  when:
    - cis_auditing_processes_prior_start | bool

- name: 4.1.1.4 Ensure audit_backlog_limit is sufficient (Scored)
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((:?(?!audit_backlog_limit=.*).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 audit_backlog_limit=8192"'
    validate: /bin/sh %s
    mode: "0664"
  notify:
    - run grub2-mkconfig
  when:
    - cis_audit_backlog_limit_sufficient | bool

- name: 4.1.2.1 Ensure audit log storage size is configured (Scored)
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^max_log_file = '
    line: max_log_file = {{ cis_audit_log_storage_size }}
  when:
    - cis_audit_log_storage_size_configured | bool

- name: 4.1.2.2 Ensure audit logs are not automatically deleted (Scored)
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^max_log_file_action = '
    line: ^max_log_file_action = keep_logs
  when:
    - cis_audit_logs_no_automatically_deleted | bool
