---
- name: 4.2.1.1 Ensure rsyslog is installed (Scored)
  package:
    name: rsyslog
    state: present
  when:
    - cis_syslog_installed | bool

- name: 4.2.1.2 Ensure rsyslog Service is enabled (Scored)
  service:
    name: rsyslog
    state: started
    enabled: yes
  when:
    - cis_rsyslog_enabled | bool

- name: 4.2.1.3 Ensure rsyslog default file permissions configured (Scored)
  lineinfile:
    path: /etc/rsyslog.d/filecreatemode.conf
    line: "$FileCreateMode 0640"
    regexp: '^\$FileCreateMode'
    mode: "0640"
    create: yes
  notify:
    - restart rsyslog
  when:
    - cis_rsyslog_file_permissions_configured | bool

- name: 4.2.1.4 Ensure logging is configured (Not Scored)
  lineinfile:
    path: /etc/rsyslog.d/rules.conf
    line: '{{ item.rule }} {{ item.destination }}'
    regex: '^{{ item.rule }}'
    mode: "0640"
    create: yes
  loop: "{{ cis_logging_site_policy }}"
  loop_control:
    label: "{{ item.rule }}"
  notify:
    - restart rsyslog
  when:
    - cis_logging_configured | bool

- name: 4.2.1.5 Ensure rsyslog is configured to send logs to a remote log host (Scored)
  lineinfile:
    path: /etc/rsyslog.d/remote_host.conf
    line: '*.* @@{{ cis_rsyslog_site_policy_host }}'
    regex: '^*.*'
    mode: "0640"
    create: yes
  when:
   - cis_rsyslog_configured_remote_log_host | bool
