---
# handlers file for cis
- name: remount /var/tmp
  mount:
    path: /var/tmp
    state: remounted

- name: remount /home
  mount:
    path: /home
    state: remounted

- name: remount /dev/shm with nodev
  command: mount -o remount,nodev /dev/shm  # noqa 303 Remounting not in module

- name: remount /dev/shm with nosuid
  command: mount -o remount,nosuid /dev/shm  # noqa 303 Remounting not in module

- name: remount /dev/shm with noexec
  command: mount -o remount,noexec /dev/shm  # noqa 303 Remounting not in module
  args:
    warn: no

- name: copy aide.db.new.gz to aide.db.gz
  copy:
    src: /var/lib/aide/aide.db.new.gz
    dest: /var/lib/aide/aide.db.gz
    mode: "0600"
    remote_src: yes

- name: run grub2-mkconfig
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: reboot
  reboot:
  when:
    - ansible_connection != "docker"

- name: update-crypto-policies
  command: update-crypto-policies

- name: restart chronyd
  service:
    name: chronyd
    state: restarted

- name: net.ipv4.route.flush
  sysctl:
    name: net.ipv4.route.flush
    value: "1"

- name: net.ipv6.route.flush
  sysctl:
    name: net.ipv6.route.flush
    value: "1"

- name: run augenrules
  command: augenrules
  notify: load rules

- name: load rules
  command: augenrules --load

- name: restart auditd
  service:
    name: auditd
    state: restarted
    use: service  # systemctl can't restart auditd, service can: https://access.redhat.com/solutions/2664811
