---
# handlers file for cis
- name: remount /tmp
  mount:
    path: /tmp
    state: remounted

- name: remount /var/tmp
  mount:
    path: /var/tmp
    state: remounted

- name: remount /home
  mount:
    path: /home
    state: remounted

- name: remount /dev/shm with nodev
  command: mount -o remount,nodev /dev/shm

- name: remount /dev/shm with nosuid
  command: mount -o remount,nosuid /dev/shm

- name: remount /dev/shm with noexec
  command: mount -o remount,noexec /dev/shm

- name: copy aide.db.new.gz to aide.db.gz
  copy:
    src: /var/lib/aide/aide.db.new.gz
    dest: /var/lib/aide/aide.db.gz
    remote_src: yes

- name: run grub2-mkconfig
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: reboot
  reboot:
