---
# handlers file for cis
- name: remount /tmp
  mount:
    path: /tmp
    state: remounted

- name: remount /var/tmp
  mount:
    path: /var/tmp
    state: remounted

- name: remount /home
  mount:
    path: /home
    state: remounted
