---
- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  command: rpm -q chrony
  register: cis_time_synchronization_test
  failed_when:
    - cis_time_synchronization_test.rc != 0
  when: 
    - cis_time_synchronization | bool

- name: 2.2.1.2 Ensure chrony is configured (Scored)
  command: grep -E "^(server|pool)" /etc/chrony.conf
  register: cis_chrony_configured_test_one
  failed_when:
    cis_chrony_configured_test_one.stdout | length == 0
  when:
    - cis_chrony_configured | bool

- name: 2.2.1.2 Ensure chrony is configured (Scored)
  command: ps -ef | grep chrony[d]
  register: cis_chrony_configured_test_two
  failed_when:
    cis_chrony_configured_test_one.stdout | length == 0
  when:
    - cis_chrony_configured | bool

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  command: rpm -qa xorg-x11*
  register: cis_x_windows_system_not_installed_test
  failed_when:
    - cis_x_windows_system_not_installed_test | length > 0
  when:
    - cis_x_windows_system_not_installed | bool
