---
- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  command: rpm -q chrony
  args:
    warn: no
  register: cis_time_synchronization_test
  failed_when:
    - cis_time_synchronization_test.rc != 0
  when: 
    - cis_time_synchronization | bool

- name: 2.2.1.2 Ensure chrony is configured (Scored)
  command: grep -E "^(server|pool)" /etc/chrony.conf
  register: cis_chrony_configured_test_one
  failed_when:
    cis_chrony_configured_test_one.stdout | length == 0
  when:
    - cis_chrony_configured | bool

- name: 2.2.1.2 Ensure chrony is configured (Scored)
  command: ps -ef | grep chrony[d]
  register: cis_chrony_configured_test_two
  failed_when:
    cis_chrony_configured_test_one.stdout | length == 0
  when:
    - cis_chrony_configured | bool

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  command: rpm -qa --qf '%{NAME}\n' xorg-x11*
  args:
    warn: no
  register: cis_x_windows_system_not_installed_test_one
  when:
    - cis_x_windows_system_not_installed | bool

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  package:
    name: "{{ item }}"
    state: absent
  check_mode: yes
  register: cis_x_windows_system_not_installed_test_two
  loop: "{{ cis_x_windows_system_not_installed_test_one.stdout_lines }}"
  failed_when:
    cis_x_windows_system_not_installed_test_two is changed
  when:
    - cis_x_windows_system_not_installed | bool

- name: 2.2.3 Ensure rsync service is not enabled (Scored)
  service:
    name: rsycnd
    state: stopped
    enabled: no
  check_mode: yes
  register: cis_rsync_service_not_enabled_test
  failed_when:
    - cis_rsync_service_not_enabled_test is changed
  when:
    -  cis_rsync_service_not_enabled
    - "'rsyncd' in services"
