---

- name: 5.1.1 Ensure cron daemon is enabled (Scored)
  service:
    name: crond
    state: started
    enabled: yes
  when:
    - cis_cron_enabled

- name: 5.1.2 Ensure permissions on /etc/crontab are configured (Scored)
  file:
    path: /etc/crontab
    owner: root
    group: root
    mode: "og-rwx"
  when:
    - cis_cron_permissions_configured

- name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured (Scored)
  file:
    path: /etc/cron.hourly
    state: directory
    owner: root
    group: root
    mode: "og-rwx"
  when:
    - cis_cron_hourly_permissions_configured
