---
# Variables for verifier, overwriting variables set in `defaults/main.yml`.

# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
# In IC, the kernel running has a different version that the one installed.
cis_cramfs_disabled: false

# 1.1.5 Ensure noexec option set on /tmp partition (Scored)
# `noexec` can't be set in a container.
cis_tmp_noexec: false

# 1.1.6 Ensure separate partition exists for /var (Scored)
# Can't create a partition in CI.
cis_var_partition: false

# 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
# Can't create a partition in CI.
cis_var_tmp_partition: false

# 1.1.11 Ensure separate partition exists for /var/log (Scored)
# Can't create a partition in CI.
cis_var_log_partition: false

# 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
# Can't create a partition in CI.
cis_var_log_audit_partition: false

# 1.1.13 Ensure separate partition exists for /home (Scored)
# Can't create a partition in CI.
cis_home_partition: false

# 1.1.23 Disable USB Storage (Scored)
# Modprobe does not work in containers.
cis_usb_storage_disabled: false

# 1.5.1 Ensure permissions on bootloader config are configured (Scored)
# No bootloaders in a container.
cis_permissions_bootloader: false

# 1.5.2 Ensure bootloader password is set (Scored)
# No bootloaders in a container.
cis_bootloader_password_set: false

# 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration (Scored)
# No bootloaders in a container.
cis_selinux_not_disabled: false

# 1.7.1.3 Ensure SELinux policy is configured (Scored)
# Can't change an SELinux policy in a container.
cis_selinux_policy_configured: false

# 1.7.1.4 Ensure the SELinux state is enforcing (Scored)
# Can't change an SELinux state in a container.
cis_selinux_state_enforcing: false

# 2.2.1.1 Ensure time synchronization is in use (Not Scored)
# Restarting chrony times out in CI. (GitLab.)
cis_time_synchronization: false

# 3.3.1 Ensure DCCP is disabled (Scored)
# can't load modules in a container.
cis_dccp_disabled: false

# 3.3.2 Ensure SCTP is disabled (Scored)
# can't load modules in a container.
cis_sctp_disabled: false

# 3.3.3 Ensure RDS is disabled (Scored)
# can't load modules in a container.
cis_rds_disabled: false

# 3.3.4 Ensure TIPC is disabled (Scored)
# can't load modules in a container.
cis_tipc_disabled: false

# 3.5 Ensure wireless interfaces are disabled (Scored)
# No NetworkManager in a container.
cis_wireless_interface_disabled: false

# 3.6 Disable IPv6 (Not Scored)
# No grub in containers.
cis_disable_ipv6: false

# 4.1.1.2 Ensure auditd service is enabled (Scored)
# For some reason auditd does not start.
cis_auditd_service_enabled: false

# 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
# No grub in containers.
cis_auditing_processes_prior_start: false

# 4.1.1.4 Ensure audit_backlog_limit is sufficient (Scored)
# No grub in containers.
cis_audit_backlog_limit_sufficient: false
