---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: load defaults/main.yml
      include_vars: ../../defaults/main.yml

    - name: load verifier overwrites
      include_vars: defaults.yml

    - name: include distribution specific version
      include: "{{ ansible_distribution ~ '-' ~ ansible_distribution_major_version }}/verify.yml"
