---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: include distribution specific version
      include: "{{ ansible_distribution ~ '-' ~ ansible_distribution_major_version }}/verify.yml"
