---
- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  package:
    name: chrony
    state: present
  when:
    - cis_time_synchronization | bool

- name: 2.2.1.2 Ensure chrony is configured (Scored)
  lineinfile:
    path: /etc/chrony.conf
    line: server {{ item }}
  notify: restart chronyd
  loop: "{{ cis_chrony_servers }}"
  when:
    - cis_time_synchronization | bool
    - cis_chrony_servers | length > 0

- name: 2.2.1.2 Ensure chrony is configured (Scored)
  lineinfile:
    path: /etc/chrony.conf
    line: pool {{ item.name }} {{ item.options }}
  notify: restart chronyd
  loop: "{{ cis_chrony_pools }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - cis_time_synchronization | bool
    - cis_chrony_pools | length > 0

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  command: rpm -qa --qf '%{NAME}\n' xorg-x11*
  args:
    warn: no
  register: cis_x_windows_system_not_installed_test_one
  when:
    - cis_x_windows_system_not_installed | bool

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  package:
    name: "{{ item }}"
    state: absent
  loop: "{{ cis_x_windows_system_not_installed_test_one.stdout_lines }}"
  when:
    - cis_x_windows_system_not_installed | bool

