---
- name: 1.6.1 Ensure core dumps are restricted (Scored)
  copy:
    dest: /etc/security/limits.d/coredumps.conf
    content: "* hard core 0"
  when:
    - cis_core_dumps_restricted

- name: 1.6.1 Ensure core dumps are restricted (Scored)
  sysctl:
    name: fs.suid_dumpable
    value: 0
  when:
    - cis_core_dumps_restricted

- name: 1.6.1 Ensure core dumps are restricted (Scored)
  package:
    name: systemd-coredump
    state: present
  check_mode: yes
  register: cis_core_dumps_restricted_test
  when:
    - cis_core_dumps_restricted

- name: 1.6.1 Ensure core dumps are restricted (Scored)
  ini_file:
    path: /etc/systemd/coredump.conf
    section: Coredump
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - option: Storage
      value: none
    - option: ProcessSizeMax
      value: 0
  when:
    - cis_core_dumps_restricted
    - cis_core_dumps_restricted_test is not changed
  notify:
    - systemctl daemon-reload
