---
# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
- name: test if cis_cramfs_disabled is set correctly
  assert:
    that:
      - cis_cramfs_disabled is defined
      - cis_cramfs_disabled | type_debug == "bool"
    quiet: yes

# 1.1.1.2 Ensure mounting of vFAT filesystems is limited (Not Scored)
- name: test if cis_vfat_disabled is set correctly
  assert:
    that:
      - cis_vfat_disabled is defined
      - cis_vfat_disabled | type_debug == "bool"
    quiet: yes

# 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
- name: test if cis_squashfs_disabled is set correctly
  assert:
    that:
      - cis_squashfs_disabled is defined
      - cis_squashfs_disabled | type_debug == "bool"
    quiet: yes

# 1.1.1.4 Ensure mounting of udf filesystems is disabled (Scored)
- name: test if cis_udf_disabled is set correctly
  assert:
    that:
      - cis_udf_disabled is defined
      - cis_udf_disabled | type_debug == "bool"
    quiet: yes

# 1.1.2 Ensure /tmp is configured (Scored)
- name: test if cis_tmp_configured is set correctly
  assert:
    that:
      - cis_tmp_configured is defined
      - cis_tmp_configured | type_debug == "bool"
    quiet: yes

# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
- name: test if cis_tmp_nodev is set correctly
  assert:
    that:
      - cis_tmp_nodev is defined
      - cis_tmp_nodev | type_debug == "bool"
    quiet: yes

# 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
- name: test if cis_tmp_nosuid is set correctly
  assert:
    that:
      - cis_tmp_nosuid is defined
      - cis_tmp_nosuid | type_debug == "bool"
    quiet: yes

# 1.1.5 Ensure noexec option set on /tmp partition (Scored)
- name: test if cis_tmp_noexec is set correctly
  assert:
    that:
      - cis_tmp_noexec is defined
      - cis_tmp_noexec | type_debug == "bool"
    quiet: yes

# 1.1.6 Ensure separate partition exists for /var (Scored)
- name: test if cis_var_partition is set correctly
  assert:
    that:
      - cis_var_partition is defined
      - cis_var_partition | type_debug == "bool"
    quiet: yes

# 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
- name: test if cis_var_tmp_partition is set correctly
  assert:
    that:
      - cis_var_tmp_partition is defined
      - cis_var_tmp_partition | type_debug == "bool"
    quiet: yes

# 1.1.8 Ensure nodev option set on /var/tmp partition (Scored)
- name: test if cis_var_tmp_nodev is set correctly
  assert:
    that:
      - cis_var_tmp_nodev is defined
      - cis_var_tmp_nodev | type_debug == "bool"
    quiet: yes

# 1.1.9 Ensure nosuid option set on /var/tmp partition (Scored)
- name: test if cis_var_tmp_nosuid is set correctly
  assert:
    that:
      - cis_var_tmp_nosuid is defined
      - cis_var_tmp_nosuid | type_debug == "bool"
    quiet: yes

# 1.1.10 Ensure noexec option set on /var/tmp partition (Scored)
- name: test if cis_var_tmp_noexec is set correctly
  assert:
    that:
      - cis_var_tmp_noexec is defined
      - cis_var_tmp_noexec | type_debug == "bool"
    quiet: yes

# 1.1.11 Ensure separate partition exists for /var/log (Scored)
- name: test if cis_var_log_partition is set correctly
  assert:
    that:
      - cis_var_log_partition is defined
      - cis_var_log_partition | type_debug == "bool"
    quiet: yes

# 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
- name: test if cis_var_log_audit_partition is set correctly
  assert:
    that:
      - cis_var_log_audit_partition is defined
      - cis_var_log_audit_partition | type_debug == "bool"
    quiet: yes

# 1.1.13 Ensure separate partition exists for /home (Scored)
- name: test if cis_home_partition is set correctly
  assert:
    that:
      - cis_home_partition is defined
      - cis_home_partition | type_debug == "bool"
    quiet: yes

# 1.1.14 Ensure nodev option set on /home partition (Scored)
- name: test if cis_home_nodev is set correctly
  assert:
    that:
      - cis_home_nodev is defined
      - cis_home_nodev | type_debug == "bool"
    quiet: yes


# 1.1.15 Ensure nodev option set on /dev/shm partition (Scored)
- name: test if cis_dev_shm_nodev is set correctly
  assert:
    that:
      - cis_dev_shm_nodev is defined
      - cis_dev_shm_nodev | type_debug == "bool"
    quiet: yes

# 1.1.16 Ensure nosuid option set on /dev/shm partition (Scored)
- name: test if cis_dev_shm_nosuid is set correctly
  assert:
    that:
      - cis_dev_shm_nosuid is defined
      - cis_dev_shm_nosuid | type_debug == "bool"
    quiet: yes

# 1.1.17 Ensure noexec option set on /dev/shm partition (Scored)
- name: test if cis_dev_shm_noexec is set correctly
  assert:
    that:
      - cis_dev_shm_noexec is defined
      - cis_dev_shm_noexec | type_debug == "bool"
    quiet: yes

# 1.1.18 Ensure nodev option set on removable media partitions (Not Scored)
- name: test if cis_removable_media_nodev is set correctly
  assert:
    that:
      - cis_removable_media_nodev is defined
      - cis_removable_media_nodev | type_debug == "bool"
    quiet: yes

# 1.1.19 Ensure nosuid option set on removable media partitions (Not Scored)
- name: test if cis_removable_media_nosuid is set correctly
  assert:
    that:
      - cis_removable_media_nosuid is defined
      - cis_removable_media_nosuid | type_debug == "bool"
    quiet: yes

# 1.1.20 Ensure noexec option set on removable media partitions (Not Scored)
- name: test if cis_removable_media_noexec is set correctly
  assert:
    that:
      - cis_removable_media_noexec is defined
      - cis_removable_media_noexec | type_debug == "bool"
    quiet: yes

# 1.1.21 Ensure sticky bit is set on all world-writable directories (Scored)
- name: test if cis_fix_sticky_bit is set correctly
  assert:
    that:
      - cis_fix_sticky_bit is defined
      - cis_fix_sticky_bit | type_debug == "bool"
    quiet: yes

# 1.1.22 Disable Automounting (Scored)
- name: test if cis_disable_automount is set correctly
  assert:
    that:
      - cis_disable_automount is defined
      - cis_disable_automount | type_debug == "bool"
    quiet: yes

# 1.1.23 Disable USB Storage (Scored)
- name: test if cis_usb_storage_disabled is set correctly
  assert:
    that:
      - cis_usb_storage_disabled is defined
      - cis_usb_storage_disabled | type_debug == "bool"
    quiet: yes

# 1.2.1 Ensure GPG keys are configured (Not Scored)
- name: test if cis_gpg_keys_configured is set correctly
  assert:
    that:
      - cis_gpg_keys_configured is defined
      - cis_gpg_keys_configured | type_debug == "bool"
    quiet: yes

# 1.2.2 Ensure gpgcheck is globally activated (Scored)
- name: test if cis_gpgcheck_enabled is set correctly
  assert:
    that:
      - cis_gpgcheck_enabled is defined
      - cis_gpgcheck_enabled | type_debug == "bool"
    quiet: yes

# 1.2.3 Ensure package manager repositories are configured (Not Scored)
- name: test if cis_repositories_configured is set correctly
  assert:
    that:
      - cis_repositories_configured is defined
      - cis_repositories_configured | type_debug == "bool"
    quiet: yes

# 1.3.1 Ensure sudo is installed (Scored)
- name: test if cis_sudo_installed is set correctly
  assert:
    that:
      - cis_sudo_installed is defined
      - cis_sudo_installed | type_debug == "bool"
    quiet: yes

# 1.3.2 Ensure sudo commands use pty (Scored)
- name: test if cis_sudo_use_pty is set correctly
  assert:
    that:
      - cis_sudo_use_pty is defined
      - cis_sudo_use_pty | type_debug == "bool"
    quiet: yes

# 1.3.3 Ensure sudo log file exists (Scored)
- name: test if cis_sudo_logfile is set correctly
  assert:
    that:
      - cis_sudo_logfile is defined
      - cis_sudo_logfile | type_debug == "bool"
    quiet: yes

# 1.4.1 Ensure AIDE is installed (Scored)
- name: test if cis_aide_installed is set correctly
  assert:
    that:
      - cis_aide_installed is defined
      - cis_aide_installed | type_debug == "bool"
    quiet: yes

# 1.4.2 Ensure filesystem integrity is regularly checked (Scored)
- name: test if cis_filesystem_integrity_checked is set correctly
  assert:
    that:
      - cis_filesystem_integrity_checked is defined
      - cis_filesystem_integrity_checked | type_debug == "bool"
    quiet: yes

# 1.5.1 Ensure permissions on bootloader config are configured (Scored)
- name: test if cis_permissions_bootloader is set correctly
  assert:
    that:
      - cis_permissions_bootloader is defined
      - cis_permissions_bootloader | type_debug == "bool"
    quiet: yes

# 1.5.2 Ensure bootloader password is set (Scored)
- name: test if cis_bootloader_password_set is set correctly
  assert:
    that:
      - cis_bootloader_password_set is defined
      - cis_bootloader_password_set | type_debug == "bool"
    quiet: yes

# 1.5.2 Ensure bootloader password is set (Scored)
- name: test if cis_bootloader_password is set correctly
  assert:
    that:
      - cis_bootloader_password is defined
      - cis_bootloader_password | length > 0
    quiet: yes
  when:
    - cis_bootloader_password_set | bool

# 1.5.3 Ensure authentication required for single user mode (Scored)
- name: test if cis_authentication_single_user_mode is set correctly
  assert:
    that:
      - cis_authentication_single_user_mode is defined
      - cis_authentication_single_user_mode | bool
    quiet: yes

# 1.6.1 Ensure core dumps are restricted (Scored)
- name: test if cis_core_dumps_restricted is set correctly
  assert:
    that:
      - cis_core_dumps_restricted is defined
      - cis_core_dumps_restricted | bool
    quiet: yes

# 1.6.2 Ensure address space layout randomization (ASLR) is enabled (Scored)
- name: test if cis_aslr_enabled is set correctly
  assert:
    that:
      - cis_aslr_enabled is defined
      - cis_aslr_enabled | bool
    quiet: yes

# 1.7.1.1 Ensure SELinux is installed (Scored)
- name: test if cis_selinux_installed is set correctly
  assert:
    that:
      - cis_selinux_installed is defined
      - cis_selinux_installed | bool
    quiet: yes
