---
# 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
- name: test if cis_cramfs_disabled is set correctly
  assert:
    that:
      - cis_cramfs_disabled is defined
      - cis_cramfs_disabled | type_debug == "bool"
    quiet: yes

# 1.1.1.2 Ensure mounting of vFAT filesystems is limited (Not Scored)
- name: test if cis_vfat_disabled is set correctly
  assert:
    that:
      - cis_vfat_disabled is defined
      - cis_vfat_disabled | type_debug == "bool"
    quiet: yes

# 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
- name: test if cis_squashfs_disabled is set correctly
  assert:
    that:
      - cis_squashfs_disabled is defined
      - cis_squashfs_disabled | type_debug == "bool"
    quiet: yes

# 1.1.1.4 Ensure mounting of udf filesystems is disabled (Scored)
- name: test if cis_udf_disabled is set correctly
  assert:
    that:
      - cis_udf_disabled is defined
      - cis_udf_disabled | type_debug == "bool"
    quiet: yes

# 1.1.2 Ensure /tmp is configured (Scored)
- name: test if cis_tmp_configured is set correctly
  assert:
    that:
      - cis_tmp_configured is defined
      - cis_tmp_configured | type_debug == "bool"
    quiet: yes

# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
- name: test if cis_tmp_nodev is set correctly
  assert:
    that:
      - cis_tmp_nodev is defined
      - cis_tmp_nodev | type_debug == "bool"
    quiet: yes

# 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
- name: test if cis_tmp_nosuid is set correctly
  assert:
    that:
      - cis_tmp_nosuid is defined
      - cis_tmp_nosuid | type_debug == "bool"
    quiet: yes

# 1.1.5 Ensure noexec option set on /tmp partition (Scored)
- name: test if cis_tmp_noexec is set correctly
  assert:
    that:
      - cis_tmp_noexec is defined
      - cis_tmp_noexec | type_debug == "bool"
    quiet: yes

# 1.1.6 Ensure separate partition exists for /var (Scored)
- name: test if cis_var_partition is set correctly
  assert:
    that:
      - cis_var_partition is defined
      - cis_var_partition | type_debug == "bool"
    quiet: yes

# 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
- name: test if cis_var_tmp_partition is set correctly
  assert:
    that:
      - cis_var_tmp_partition is defined
      - cis_var_tmp_partition | type_debug == "bool"
    quiet: yes

# 1.1.8 Ensure nodev option set on /var/tmp partition (Scored)
- name: test if cis_var_tmp_nodev is set correctly
  assert:
    that:
      - cis_var_tmp_nodev is defined
      - cis_var_tmp_nodev | type_debug == "bool"
    quiet: yes

# 1.1.9 Ensure nosuid option set on /var/tmp partition (Scored)
- name: test if cis_var_tmp_nosuid is set correctly
  assert:
    that:
      - cis_var_tmp_nosuid is defined
      - cis_var_tmp_nosuid | type_debug == "bool"
    quiet: yes

# 1.1.10 Ensure noexec option set on /var/tmp partition (Scored)
- name: test if cis_var_tmp_noexec is set correctly
  assert:
    that:
      - cis_var_tmp_noexec is defined
      - cis_var_tmp_noexec | type_debug == "bool"
    quiet: yes

# 1.1.11 Ensure separate partition exists for /var/log (Scored)
- name: test if cis_var_log_partition is set correctly
  assert:
    that:
      - cis_var_log_partition is defined
      - cis_var_log_partition | type_debug == "bool"
    quiet: yes

# 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
- name: test if cis_var_log_audit_partition is set correctly
  assert:
    that:
      - cis_var_log_audit_partition is defined
      - cis_var_log_audit_partition | type_debug == "bool"
    quiet: yes

# 1.1.13 Ensure separate partition exists for /home (Scored)
- name: test if cis_home_audit_partition is set correctly
  assert:
    that:
      - cis_home_audit_partition is defined
      - cis_home_audit_partition | type_debug == "bool"
    quiet: yes

# 1.1.14 Ensure nodev option set on /home partition (Scored)
- name: test if cis_home_nodev is set correctly
  assert:
    that:
      - cis_home_nodev is defined
      - cis_home_nodev | type_debug == "bool"
    quiet: yes


# 1.1.15 Ensure nodev option set on /dev/shm partition (Scored)
- name: test if cis_dev_shm_nodev is set correctly
  assert:
    that:
      - cis_dev_shm_nodev is defined
      - cis_dev_shm_nodev | type_debug == "bool"
    quiet: yes

# 1.1.16 Ensure nosuid option set on /dev/shm partition (Scored)
- name: test if cis_dev_shm_nosuid is set correctly
  assert:
    that:
      - cis_dev_shm_nosuid is defined
      - cis_dev_shm_nosuid | type_debug == "bool"
    quiet: yes

# 1.1.17 Ensure noexec option set on /dev/shm partition (Scored)
- name: test if cis_dev_shm_noexec is set correctly
  assert:
    that:
      - cis_dev_shm_noexec is defined
      - cis_dev_shm_noexec | type_debug == "bool"
    quiet: yes

# 1.1.18 Ensure nodev option set on removable media partitions (Not Scored)
- name: test if cis_removable_media_nodev is set correctly
  assert:
    that:
      - cis_removable_media_nodev is defined
      - cis_removable_media_nodev | type_debug == "bool"
    quiet: yes
