---
- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  copy:
    content: "install cramfs /bin/true"
    dest: /etc/modprobe.d/cramfs.conf

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  modprobe:
    name: cramfs
    state: absent

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is limited (Not Scored)
  copy:
    content: "install vfat /bin/true"
    dest: /etc/modprobe.d/vfat.conf

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is limited (Not Scored)
  modprobe:
    name: vfat
    state: absent

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  copy:
    content: "install squashfs /bin/true"
    dest: /etc/modprobe.d/squashfs.conf

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  modprobe:
    name: squashfs
    state: absent
