---
- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  copy:
    content: "install cramfs /bin/true"
    dest: /etc/modprobe.d/cramfs.conf
  when:
    - cis_cramfs_disabled | bool

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  modprobe:
    name: cramfs
    state: absent
  when:
    - cis_cramfs_disabled | bool
    - ansible_virtualization_type != "docker"

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is limited (Not Scored)
  copy:
    content: "install vfat /bin/true"
    dest: /etc/modprobe.d/vfat.conf
  when:
    - cis_vfat_disabled | bool

- name: 1.1.1.2 Ensure mounting of vFAT filesystems is limited (Not Scored)
  modprobe:
    name: vfat
    state: absent
  when:
    - cis_vfat_disabled | bool
    - ansible_virtualization_type != "docker"

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  copy:
    content: "install squashfs /bin/true"
    dest: /etc/modprobe.d/squashfs.conf
  when:
    - cis_squashfs_disabled | bool

- name: 1.1.1.3 Ensure mounting of squashfs filesystems is disabled (Scored)
  modprobe:
    name: squashfs
    state: absent
  when:
    - cis_squashfs_disabled | bool
    - ansible_virtualization_type != "docker"

- name: 1.1.1.4 Ensure mounting of udf filesystems is disabled (Scored)
  copy:
    content: "install udf /bin/true"
    dest: /etc/modprobe.d/udf.conf
  when:
    - cis_udf_disabled | bool

- name: 1.1.1.4 Ensure mounting of udf filesystems is disabled (Scored)
  modprobe:
    name: udf
    state: absent
  when:
    - cis_udf_disabled | bool
    - ansible_virtualization_type != "docker"

- name: 1.1.2 Ensure /tmp is configured (Scored)
  systemd:
    name: tmp.mount
    state: started
    enabled: yes
  when:
    - cis_tmp_configured | bool

- name: 1.1.3 Ensure nodev option set on /tmp partition (Scored)
  mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},nodev"
    state: present
  with_items: ansible_mounts
  when:
    - cis_tmp_nodev | bool
    - item.mount == "/tmp"
    - item.options.find(",") >= 0
    - item.options.find("nodev") == -1
  notify:
    - remount /tmp

- name: 1.1.4 Ensure nosuid option set on /tmp partition (Scored)
  mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},nosuid"
    state: present
  with_items: ansible_mounts
  when:
    - cis_tmp_nosuid | bool
    - item.mount == "/tmp"
    - item.options.find(",") >= 0
    - item.options.find("nosuid") == -1
  notify:
    - remount /tmp

- name: 1.1.5 Ensure noexec option set on /tmp partition (Scored)
  mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},noexec"
    state: present
  with_items: ansible_mounts
  when:
    - cis_tmp_noexec | bool
    - item.mount == "/tmp"
    - item.options.find(",") >= 0
    - item.options.find("noexec") == -1
  notify:
    - remount /tmp
