---
# This task should be moved to `tasks/main.yml`, but due to an issue on Ubuntu
# it's called here, just for CentOS.
- name: populate service facts
  service_facts:

# 1.1 Filesystem Configuration
- name: include filesystem_configuration.yml
  include: initial_setup/filesystem_configuration.yml

# 1.2 Configure Software Updates
- name: include configure_software_updates.yml
  include: initial_setup/configure_software_updates.yml

# 1.3 Configure sudo
- name: include configure_sudo.yml
  include: initial_setup/configure_sudo.yml

# 1.4 Filesystem Integrity Checking
- name: include filesystem_integrity_checking.yml
  include: initial_setup/filesystem_integrity_checking.yml

# 1.5 Secure Boot Settings
- name: include secure_boot_settings.yml
  include: initial_setup/secure_boot_settings.yml

# 1.6 Additional Process Hardening
- name: include additional_process_hardening.yml
  include: initial_setup/additional_process_hardening.yml

# 1.7 Mandatory Access Control
- name: include mandatory_access_control.yml
  include: initial_setup/mandatory_access_control.yml

# 1.8 Warning Banners
- name: include warning_banners.yml
  include: initial_setup/warning_banners.yml

# 1.9 Ensure updates, patches, and additional security software are installed (Not Scored)
- name: include updates_installed.yml
  include: initial_setup/updates_installed.yml

# name: 1.10 Ensure system-wide crypto policy is not legacy (Scored)
- name: include system_wide_crypto_policy.yml
  include: initial_setup/system_wide_crypto_policy.yml

# 2.1 inetd Services
- name: include inetd_services.yml
  include: services/inetd_services.yml

# 2.2 Special Purpose Services
- name: include special_purpose_services.yml
  include: services/special_purpose_services.yml

# 2.2 Service Clients
- name: include service_clients.yml
  include: services/service_clients.yml

# 3.1 Network Parameters
- name: include network_parameters.yml
  include: network/network_parameters.yml

# 3.2 Network Parameters (Host and Router)
- name: include network_parameters_host_and_router.yml
  include: network/network_parameters_host_and_router.yml
