---
# This task should be moved to `tasks/main.yml`, but due to an issue on Ubuntu
# it's called here, just for CentOS.
- name: populate service facts
  service_facts:

- name: include initial_setup.yml
  include: initial_setup.yml

- name: include configure_software_updates.yml
  include: configure_software_updates.yml

- name: include configure_sudo.yml
  include: configure_sudo.yml

- name: include filesystem_integrity_checking.yml
  include: filesystem_integrity_checking.yml

- name: include secure_boot_settings.yml
  include: secure_boot_settings.yml
