---
- name: 1.7.1.1 Ensure SELinux is installed (Scored)
  package:
    name: libselinux
    state: present
  register: cis_selinux_installed_test
  when:
    - cis_selinux_installed

- name: 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration (Scored)
  lineinfile:
    path: /etc/default/grub
    regexp: '^(.*)(selinux=0)(.*)'
    line: '\1 \3'
    backrefs: true
  when:
    - cis_selinux_not_disabled
  notify:
    - run grub2-mkconfig

- name: 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration (Scored)
  lineinfile:
    path: /etc/default/grub
    regexp: '^(.*)(enforcing=0)(.*)'
    line: '\1 \3'
    backrefs: true
  when:
    - cis_selinux_not_disabled
  notify:
    - run grub2-mkconfig

- name: 1.7.1.3 Ensure SELinux policy is configured (Scored)
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUXTYPE='
    line: "SELINUXTYPE={{ cis_selinux_policy }}"
  when:
    - cis_selinux_policy_configured
  notify:
    - reboot
