---
- name: 1.5.1 Ensure permissions on bootloader config are configured (Scored)
  stat:
    path: "{{ item }}"
  register: cis_bootloader_files
  loop:
    - /boot/grub2/grub.cfg
    - /boot/grub2/grubenv
  when:
    - cis_permissions_bootloader | bool
  
- name: 1.5.1 Ensure permissions on bootloader config are configured (Scored)
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: g-rwx,o-rwx
  loop: "{{ cis_bootloader_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - cis_bootloader_files.files is defined
    - cis_permissions_bootloader | bool

- name: 1.5.2 Ensure bootloader password is set (Scored)
  pip:
    name: pexpect
    state: present
  when:
    - cis_bootloader_password_set | bool

- name: 1.5.2 Ensure bootloader password is set (Scored)
  package:
    name: "{{ item }}"
    state: present
  loop:
    - grub2-tools
    - grub2-tools-minimal
  when:
    - cis_bootloader_password_set | bool

- name: 1.5.2 Ensure bootloader password is set (Scored)
  expect:
    command: grub2-setpassword
    responses:
      "Enter password: ": "{{ cis_bootloader_password }}"
      "Confirm password: ": "{{ cis_bootloader_password }}"
    creates: /boot/grub2/user.cfg
  # no_log: true
  when:
    - cis_bootloader_password_set | bool
  notify:
    - run grub2-mkconfig
