---
- name: 1.8.1.1 Ensure message of the day is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/motd
  when:
    - cis_message_of_the_day_configured

- name: 1.8.1.2 Ensure local login warning banner is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/issue
  when:
    - cis_local_login_banner_configured | bool


- name: 1.8.1.3 Ensure remote login warning banner is configured properly (Scored)
  copy:
    content: "{{ cis_message_of_the_day }}"
    dest: /etc/issue.net
  when:
    - cis_remote_login_banner_configured | bool

