---
- name: 1.9 Ensure updates, patches, and additional security software are installed (Not Scored)
  package:
    name: "*"
    state: latest  # noqa 403
  notify:
    - reboot
  when:
    - cis_updates_installed | bool
