---
- name: 4.1.1.1 Ensure auditd is installed (Scored)
  package:
    name:
      - audit
      - audit-libs
    state: present
  check_mode: yes
  register: cis_auditd_installed_test
  failed_when:
    - cis_auditd_installed_test is changed
  when:
    - cis_auditd_installed | bool

- name: 4.1.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    state: started
    enabled: yes
  check_mode: yes
  register: cis_auditd_service_enabled_test
  failed_when:
    - cis_auditd_service_enabled_test is changed
  when:
    - cis_auditd_service_enabled | bool

- name: 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  command: grep -E 'kernelopts=(\S+\s+)*audit=1\b' /boot/grub2/grubenv
  register: cis_auditing_processes_prior_start_test
  failed_when:
    - "'audit=1' not in cis_auditing_processes_prior_start_test.stdout"
  when:
    - cis_auditing_processes_prior_start | bool
