---
- name: 4.1.1.1 Ensure auditd is installed (Scored)
  package:
    name:
      - audit
      - audit-libs
    state: present
  check_mode: yes
  register: cis_auditd_installed_test
  failed_when:
    - cis_auditd_installed_test is changed
  when:
    - cis_auditd_installed | bool

- name: 4.1.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    state: started
    enabled: yes
  check_mode: yes
  register: cis_auditd_service_enabled_test
  failed_when:
    - cis_auditd_service_enabled_test is changed
  when:
    - cis_auditd_service_enabled | bool
