---
- name: 4.1.1.1 Ensure auditd is installed (Scored)
  package:
    name:
      - audit
      - audit-libs
    state: present
  check_mode: yes
  register: cis_auditd_installed_test
  failed_when:
    - cis_auditd_installed_test is changed
  when:
    - cis_auditd_installed | bool

- name: 4.1.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    state: started
    enabled: yes
  check_mode: yes
  register: cis_auditd_service_enabled_test
  failed_when:
    - cis_auditd_service_enabled_test is changed
  when:
    - cis_auditd_service_enabled | bool

- name: 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  command: grep -E 'kernelopts=(\S+\s+)*audit=1\b' /boot/grub2/grubenv
  register: cis_auditing_processes_prior_start_test
  failed_when:
    - "'audit=1' not in cis_auditing_processes_prior_start_test.stdout"
  when:
    - cis_auditing_processes_prior_start | bool

- name: 4.1.1.4 Ensure audit_backlog_limit is sufficient (Scored)
  command: grep -E 'kernelopts=(\S+\s+)*audit_backlog_limit=\S+\b' /boot/grub2/grubenv
  register: cis_audit_backlog_limit_sufficient_test
  failed_when:
    - "'audit_backlog_limit=8192' not in cis_audit_backlog_limit_sufficient_test.stdout"
  when:
    - cis_audit_backlog_limit_sufficient | bool

- name: 4.1.2.1 Ensure audit log storage size is configured (Scored)
  command: grep "max_log_file = {{ cis_audit_log_storage_size }}" /etc/audit/auditd.conf
  when:
    - cis_audit_log_storage_size_configured | bool

- name: 4.1.2.2 Ensure audit logs are not automatically deleted (Scored)
  command: grep "max_log_file_action = keep_logs" /etc/audit/auditd.conf
  when:
    - cis_audit_logs_no_automatically_deleted | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  command: grep "space_left_action = email" /etc/audit/auditd.conf
  when:
    - cis_system_disabled_audit_logs_full | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  command: grep "action_mail_acct = root" /etc/audit/auditd.conf
  when:
    - cis_system_disabled_audit_logs_full | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  command: grep "admin_space_left_action = halt" /etc/audit/auditd.conf
  when:
    - cis_system_disabled_audit_logs_full | bool

- name: 4.1.3 Ensure changes to system administration scope (sudoers) is collected (Scored)
  command: grep scope /etc/audit/rules.d/*.rules
  register: cis_changed_to_system_administrator_scope_collected_test
  failed_when:
    - "'-w /etc/sudoers -p wa -k scope' not in cis_changed_to_system_administrator_scope_collected_test.stdout or
       '-w /etc/sudoers.d/ -p wa -k scope' not in cis_changed_to_system_administrator_scope_collected_test.stdout"
  when:
    - cis_changed_to_system_administrator_scope_collected | bool

- name: 4.1.4 Ensure login and logout events are collected (Scored)
  command: grep logins /etc/audit/rules.d/*.rules
  register: cis_login_and_login_events_collected_test_one
  failed_when:
    - "'-w /var/log/faillog -p wa -k logins' not in cis_login_and_login_events_collected_test_one.stdout"
    - "'-w /var/log/lastlog -p wa -k logins' not in cis_login_and_login_events_collected_test_one.stdout"
  when:
    - cis_login_and_login_events_collected | bool

- name: 4.1.4 Ensure login and logout events are collected (Scored)
  command: auditctl -l | grep logins
  register: cis_login_and_login_events_collected_test_two
  failed_when:
    - "'-w /var/log/faillog -p wa -k logins' not in cis_login_and_login_events_collected_test_two.stdout"
    - "'-w /var/log/lastlog -p wa -k logins' not in cis_login_and_login_events_collected_test_two.stdout"
  when:
    - cis_login_and_login_events_collected | bool

- name: 4.1.5 Ensure session initiation information is collected (Scored)
  command: grep -E '(session|logins)' /etc/audit/rules.d/*.rules
  register: cis_session_initiation_information_collected_test_one
  failed_when:
    - "'-w /var/run/utmp -p wa -k session' not in cis_session_initiation_information_collected_test_one.stdout"
    - "'-w /var/run/wtmp -p wa -k logins' not in cis_session_initiation_information_collected_test_one.stdout"
    - "'-w /var/run/btmp -p wa -k logins' not in cis_session_initiation_information_collected_test_one.stdout"
  when:
    - cis_session_initiation_information_collected | bool

- name: 4.1.5 Ensure session initiation information is collected (Scored)
  shell: auditctl -l | grep -E '(session|logins)'
  register: cis_session_initiation_information_collected_test_two
  failed_when:
    - "'-w /var/run/utmp -p wa -k session' not in cis_session_initiation_information_collected_test_two.stdout"
    - "'-w /var/run/wtmp -p wa -k logins' not in cis_session_initiation_information_collected_test_two.stdout"
    - "'-w /var/run/btmp -p wa -k logins' not in cis_session_initiation_information_collected_test_two.stdout"
  when:
    - cis_session_initiation_information_collected | bool

- name: 4.1.6 Ensure events that modify date and time information are collected (Scored)
  command: grep -E '(session|logins)' /etc/audit/rules.d/*.rules
  register: cis_events_modify_time_and_date_collected_test_one
  failed_when:
    - "'-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change' not in cis_events_modify_time_and_date_collected_test_one.stdout"
    - "'-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change' not in cis_events_modify_time_and_date_collected_test_one.stdout"
    - "'-a always,exit -F arch=b64 -S clock_settime -k time-change' not in cis_events_modify_time_and_date_collected_test_one.stdout"
    - "'-a always,exit -F arch=b32 -S clock_settime -k time-change' not in cis_events_modify_time_and_date_collected_test_one.stdout"
    - "'-w /etc/localtime -p wa -k time-change' not in cis_events_modify_time_and_date_collected_test_one.stdout"
  when:
    - cis_events_modify_time_and_date_collected | bool

- name: 4.1.6 Ensure events that modify date and time information are collected (Scored)
  shell: auditctl -l | grep time-change
  register: cis_events_modify_time_and_date_collected_test_two
  failed_when:
    - "'-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change' not in cis_events_modify_time_and_date_collected_test_two.stdout"
    - "'-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change' not in cis_events_modify_time_and_date_collected_test_two.stdout"
    - "'-a always,exit -F arch=b64 -S clock_settime -k time-change' not in cis_events_modify_time_and_date_collected_test_two.stdout"
    - "'-a always,exit -F arch=b32 -S clock_settime -k time-change' not in cis_events_modify_time_and_date_collected_test_two.stdout"
    - "'-w /etc/localtime -p wa -k time-change' not in cis_events_modify_time_and_date_collected_test_two.stdout"
  when:
    - cis_events_modify_time_and_date_collected | bool
