---
- name: 4.1.1.1 Ensure auditd is installed (Scored)
  package:
    name:
      - audit
      - audit-libs
    state: present
  check_mode: yes
  register: cis_auditd_installed_test
  failed_when:
    - cis_auditd_installed_test is changed
  when:
    - cis_auditd_installed | bool

- name: 4.1.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    state: started
    enabled: yes
  check_mode: yes
  register: cis_auditd_service_enabled_test
  failed_when:
    - cis_auditd_service_enabled_test is changed
  when:
    - cis_auditd_service_enabled | bool

- name: 4.1.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  command: grep -E 'kernelopts=(\S+\s+)*audit=1\b' /boot/grub2/grubenv
  register: cis_auditing_processes_prior_start_test
  failed_when:
    - "'audit=1' not in cis_auditing_processes_prior_start_test.stdout"
  when:
    - cis_auditing_processes_prior_start | bool

- name: 4.1.1.4 Ensure audit_backlog_limit is sufficient (Scored)
  command: grep -E 'kernelopts=(\S+\s+)*audit_backlog_limit=\S+\b' /boot/grub2/grubenv
  register: cis_audit_backlog_limit_sufficient_test
  failed_when:
    - "'audit_backlog_limit=8192' not in cis_audit_backlog_limit_sufficient_test.stdout"
  when:
    - cis_audit_backlog_limit_sufficient | bool

- name: 4.1.2.1 Ensure audit log storage size is configured (Scored)
  command: grep "max_log_file = {{ cis_audit_log_storage_size }}" /etc/audit/auditd.conf
  when:
    - cis_audit_log_storage_size_configured | bool

- name: 4.1.2.2 Ensure audit logs are not automatically deleted (Scored)
  command: grep "max_log_file_action = keep_logs" /etc/audit/auditd.conf
  when:
    - cis_audit_logs_no_automatically_deleted | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  command: grep "space_left_action = email" /etc/audit/auditd.conf
  when:
    - cis_system_disabled_audit_logs_full | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  command: grep "action_mail_acct = root" /etc/audit/auditd.conf
  when:
    - cis_system_disabled_audit_logs_full | bool

- name: 4.1.2.3 Ensure system is disabled when audit logs are full (Scored)
  command: grep "admin_space_left_action = halt" /etc/audit/auditd.conf
  when:
    - cis_system_disabled_audit_logs_full | bool
