---
- name: 4.2.1.1 Ensure rsyslog is installed (Scored)
  command: rpm -q rsyslog
  when:
    - cis_syslog_installed | bool

- name: 4.2.1.2 Ensure rsyslog Service is enabled (Scored)
  service:
    name: rsyslog
    state: started
    enabled: yes
  check_mode: yes
  register: cis_rsyslog_enabled_test_one
  failed_when:
    - cis_rsyslog_enabled_test_one is changed
  when:
    - cis_rsyslog_enabled | bool

- name: 4.2.1.3 Ensure rsyslog default file permissions configured (Scored)
  shell: grep "^\$FileCreateMode" /etc/rsyslog.conf /etc/rsyslog.d/*.conf
  register: cis_rsyslog_file_permissions_configured_test_one
  failed_when:
    - "'0640' not in cis_rsyslog_file_permissions_configured_test_one.stdout"
  when:
    - cis_rsyslog_file_permissions_configured | bool

- name: 4.2.1.4 Ensure logging is configured (Not Scored)
  lineinfile:
    path: /etc/rsyslog.d/rules.conf
    line: "{{ item.rule }} {{ item.destination }}"
    regex: '^{{ item.rule }}'
    mode: "0640"
    create: yes
  check_mode: yes
  register: cis_logging_configured_test_one
  failed_when:
    - cis_logging_configured_test_one is changed
  loop: "{{ cis_logging_site_policy }}"
  loop_control:
    label: "{{ item.rule }}"
  when:
    - cis_logging_configured: yes

- name: 4.2.1.5 Ensure rsyslog is configured to send logs to a remote log host (Scored)
  shell: |-
    "grep "^*.*[^I][^I]*@" /etc/rsyslog.conf /etc/rsyslog.d/*.conf"
  register: cis_rsyslog_configured_remote_log_host_test_one
  when:
   - cis_rsyslog_configured_remote_log_host | bool
